### ISSUE TITLE
With empack 0.4.1, jupyterlite-xeus ships empty tarballs for pip installed packages

### ISSUE THREAD

**Issue by nthiery** [emscripten-forge/empack#105]
* empack version: 4.0.1
* Operating System: Ubuntu 24.04
* Compiler: gcc 13.2.0

### Description

I am building a jupyterlite-xeus site which uses some custom Python packages, with the versions of jupyterlite currently shipped by default with conda. The python packages are then non functional in jupyterlite, and this is caused by the kernel package tarballs to be empty (upto the metadata json file). Downgrading to empack to 4.0.0 resolves the problem. I have tried with various versions of jupyterlite-core and xeus (including beta) and this has no influence.

### How to reproduce

My current `build-environment.yml` now forces empack 4.0.0. After building the site, the tarball
is filled up with a couple python and png files, as desired:
```
git clone https://gitlab-research.centralesupelec.fr/IntroductionProgrammationPython/introductionprogrammationpython.pages.centralesupelec.fr.git
mamba env create -f build-environment.yml
conda activate cours-python-build
make lite
tar ztvf _build/html/lite/xeus/kernel_packages/laby_python-0.0.5-pip.tar.gz
```

However, after upgrading to 4.0.1, the tarball is empty (up to metadata):
```
mamba install empack==0.4.1
make lite
tar ztvf _build/html/lite/xeus/kernel_packages/laby_python-0.0.5-pip.tar.gz
```

**Comment by martinRenou** [comment]
Thanks for reporting. It seems https://github.com/emscripten-forge/empack/pull/104 was the only PR merged so that should be the culprit. My bad for not testing it properly.

We should revert it for now.

**Comment by nthiery** [comment]
Thanks for the quick feedback!

**Comment by martinRenou** [comment]
I reverted it and am making a release right now
