### ISSUE TITLE
Add ability to relocate the root prefix of the packed env

### ISSUE THREAD

**Issue by martinRenou** [emscripten-forge/empack#61]
### Description

When packing an environment, the in-memory Emscripten file-system becomes the same as the real file system from which it was generated, with the same root prefix. *e.g.* the files generated in the CI of xeus-python will have the root-prefix `/home/runner/micromamba-root/envs/xeus-python-wasm-host`

It would be nice to be able to configure the root prefix (maybe with a simple search and replace in the generated files?).

**Comment by DerThorsten** [comment]
This is done in #66
